### ISSUE TITLE
Please, add javadoc and source code to the gradle artifact

### ISSUE THREAD

**Issue by netimen** [JakeWharton/scalpel#24]
Currently there is neither javadoc nor source code included. I now there used to be some problems shipping javadoc and source code in aar files, but they seem to have been fixed

**Comment by JakeWharton** [comment]
Javadoc and sources jars are required for publishing to Maven central, and you can see that they are available here (at the bottom): http://search.maven.org/#artifactdetails%7Ccom.jakewharton.scalpel%7Cscalpel%7C1.1.2%7Cjar
